export const BEGIN_API_CALL = "BEGIN_API_CALL";
export const API_CALL_ERROR = "API_CALL_ERROR";

export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAILURE = "SIGNUP_FAILURE";

export const SIGNIN_USER_SUCCESS = "SINGIN_USER_SUCCESS";
export const SIGNIN_USER_FAILURE = "SIGNIN_USER_FAILURE";
export const SINGOUT_USER = "SINGOUT_USER"; // no _SUCCESS suffix - there is no api call

export const USERS_LOAD_SUCCESS = "USERS_LOAD_SUCCESS";

export const POST_GAME_SUCCESS = "POST_GAME_SUCCESS";
export const POST_GAME_FAILURE = "POST_GAME_FAILURE";
export const LIBRARY_LOAD_SUCCESS = "LIBRARY_LOAD_SUCCESS";
export const LIBRARY_LOAD_FALILURE = "LIBRARY_LOAD_FAILURE";
export const LOAD_GAMES_SUCCESS = "LOAD_GAMES_SUCCESS";
export const LOAD_GAMES_FAILURE = "LOAD_GAMES_FAILURE";
export const POST_GAME_AUCTION_SUCCESS = "POST_GAME_AUCTION_SUCCESS";
export const POST_GAME_AUCTION_FALIRE= "POST_GAME_AUCTION_FALIRE";
export const DELETE_GAME_SUCCESS = "DELETE_GAME_SUCCESS";
export const DELETE_GAME_FAIlURE = "DELETE_GAME_FAILURE";
